- name: Ensure target_host is specified
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check for target_host variable
      fail:
        msg: "You must specify a target_host variable."
      when: target_host is not defined
      
- name: Deploy NixOS using nixos-anywhere
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Ensure /tmp/nixos-setup exists
      ansible.builtin.file:
        path: /tmp/nixos-setup
        state: directory

    - name: Copy disk configuration to remote machine
      ansible.builtin.copy:
        src: "{{ disk_config_path }}"
        dest: "/tmp/nixos-setup/disk-config.nix"

    - name: Install NixOS on the target machine using nixos-anywhere
      ansible.builtin.shell: |
        nix run github:nix-community/nixos-anywhere -- --flake github:nix-community/nixos-anywhere-examples#{{ flake_name }} --disk-config /tmp/nixos-setup/disk-config.nix root@{{ inventory_hostname }}
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Wait for the machine to reboot
      ansible.builtin.wait_for_connection:
        delay: 60
        timeout: 300

    - name: Update known_hosts file to remove old host key
      ansible.builtin.shell: |
        ssh-keygen -f "$HOME/.ssh/known_hosts" -R "{{ inventory_hostname }}"
      delegate_to: localhost
      
    - name: Install agenix on the target machine TODO
      ansible.builtin.shell: |
        sudo nix-channel --add https://github.com/ryantm/agenix/archive/main.tar.gz agenix && sudo nix-channel --update
      args:
        executable: /bin/bash

    # Generate ed25519 ssh key pair
    - name: Generate ed25519 ssh key pair
      ansible.builtin.shell: |
        ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N ""
      args:
        executable: /bin/bash

    # Pause to add that key to the flake
    - name: Pause to add that key to the flake
      ansible.builtin.pause:
        prompt: "Add the following key to the flake (add to secrets.nix and re-encrypt with agenix -r) and press Enter to continue: {{ lookup('file', '/root/.ssh/id_ed25519.pub') }}"

    - name: Apply custom flake configuration
      ansible.builtin.shell: |
        nixos-rebuild switch --flake github:yourusername/yourflakerepo#{{ flake_name }} --target-host root@{{ inventory_hostname }}
      args:
        executable: /bin/bash
      environment:
        NIX_PATH: nixpkgs=channel:nixos-unstable

