- name: Ensure target_host is specified
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check for target_host variable
      fail:
        msg: "You must specify a target_host variable."
      when: target_host is not defined

- name: Deploy NixOS using nixos-anywhere
  hosts: all
  gather_facts: no
  become: yes
  tasks:

    - name: Ensure known_hosts does not contain old host key by IP
      ansible.builtin.lineinfile:
        path: "{{ lookup('env','HOME') }}/.ssh/known_hosts"
        regexp: '^{{ ansible_host }} '
        state: absent
      delegate_to: localhost

    - name: Ensure known_hosts does not contain old host key by hostname
      ansible.builtin.lineinfile:
        path: "{{ lookup('env','HOME') }}/.ssh/known_hosts"
        regexp: '^{{ inventory_hostname }} '
        state: absent
      delegate_to: localhost

    - name: Bootstrap.sh prompt
      ansible.builtin.pause:
        prompt: "Run bootstrap.sh on the remote machine and press enter when done"
      delegate_to: localhost

    - name: Print the SSH public key and prompt to add it
      ansible.builtin.shell:
        cmd: sudo cat /etc/ssh/ssh_host_ed25519_key.pub
      register: ssh_public_key
      delegate_to: localhost
      run_once: true
      become: yes

    - name: Prompt to add the SSH public key to the flake and secrets.nix
      ansible.builtin.pause:
        prompt: |
          Add the following SSH public key to secrets.nix for {{ inventory_hostname }}:
          {{ ssh_public_key.stdout }}
          Press enter once done.
      delegate_to: localhost
      run_once: true

    - name: Agenix --rekey prompt
      ansible.builtin.pause:
        prompt: "Run `agenix --rekey` and press enter when done"
      delegate_to: localhost

    - name: Commit and push prompt
      ansible.builtin.pause:
        prompt: "Commit the changes to the flake and push the changes. Press enter when done"
      delegate_to: localhost

    - name: Clone the nix-infra repository
      ansible.builtin.shell:
        cmd: >
          git clone https://github.com/blakeashleyjr/nix-infra.git
      args:
        executable: /run/current-system/sw/bin/bash

    - name: Run the disko command
      ansible.builtin.shell:
        cmd: >
          sudo nix --experimental-features "nix-command flakes" run github:nix-community/disko -- --mode disko ./nix-infra/hypervisors/hv-2/hv-2-disk-config.nix
      args:
        executable: /run/current-system/sw/bin/bash

    - name: Copy git repo to new install root user
      ansible.builtin.shell:
        cmd: >
          sudo cp -r ./nix-infra /mnt/root/
      args:
        executable: /run/current-system/sw/bin/bash

    # Run install command
    - name: Stop to run command manually
      ansible.builtin.pause:
        prompt: "Stop to run command manually"
      delegate_to: localhost

    - name: Copy ssh hostkey to new install
      ansible.builtin.shell:
        cmd: >
          sudo cp -r /etc/ssh/* /mnt/etc/ssh/
      args:
        executable: /run/current-system/sw/bin/bash
    # Set root password for testing so I can troubleshoot network issues

    # Check if the host key is unchanged

    - name: Wait for the machine to reboot
      ansible.builtin.wait_for_connection:
        delay: 60
        timeout: 300
