- name: Ensure target_host is specified
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check for target_host variable
      fail:
        msg: "You must specify a target_host variable."
      when: target_host is not defined
      
- name: Deploy NixOS using nixos-anywhere
  hosts: all
  gather_facts: no
  become: yes
  tasks:

    - name: Install NixOS on the target machine using local clone of nixos-anywhere
      ansible.builtin.shell:
        cmd: >
          nix run ./ 
          --extra-experimental-features "nix-command flakes" 
          -- --flake .#{{ inventory_hostname }}
          --disk-config /tmp/nixos-setup/disk-config.nix root@{{ ansible_host }}
      args:
        executable: /run/current-system/sw/bin/bash
      delegate_to: localhost


    # - name: Wait for the machine to reboot
    #   ansible.builtin.wait_for_connection:
    #     delay: 60
    #     timeout: 300

    # - name: Update known_hosts file to remove old host key
    #   ansible.builtin.shell: |
    #     ssh-keygen -f "$HOME/.ssh/known_hosts" -R "{{ ansible_host }}"
    #   delegate_to: localhost
      
    # - name: Install agenix on the target machine TODO
    #   ansible.builtin.shell: |
    #     sudo nix-channel --add https://github.com/ryantm/agenix/archive/main.tar.gz agenix && sudo nix-channel --update
    #   args:
    #     executable: /run/current-system/sw/bin/bash

    # # Generate ed25519 ssh key pair
    # - name: Generate ed25519 ssh key pair
    #   ansible.builtin.shell: |
    #     ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N ""
    #   args:
    #     executable: /run/current-system/sw/bin/bash

    # # Pause to add that key to the flake
    # - name: Pause to add that key to the flake
    #   ansible.builtin.pause:
    #     prompt: "Add the following key to the flake (add to secrets.nix and re-encrypt with agenix -r) and press Enter to continue: {{ lookup('file', '/root/.ssh/id_ed25519.pub') }}"

    # - name: Apply custom flake configuration
    #   ansible.builtin.shell: |
    #     nixos-rebuild switch --flake github:blakeashleyjr/nix-infra#hv-2 --target-host root@{{ inventory_hostname }}
    #   args:
    #     executable: /run/current-system/sw/bin/bash
    #   environment:
    #     NIX_PATH: nixpkgs=channel:nixos-unstable

