- name: Ensure target_host is specified
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check for target_host variable
      fail:
        msg: "You must specify a target_host variable."
      when: target_host is not defined

- name: Deploy NixOS using nixos-anywhere
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Remove old private key in /tmp
      ansible.builtin.file:
        path: /tmp/id_ed25519
        state: absent
      delegate_to: localhost
      run_once: true
    
    - name: Remove old public key in /tmp
      ansible.builtin.file:
        path: /tmp/id_ed25519.pub
        state: absent
      delegate_to: localhost
      run_once: true
    
    - name: Generate an ED25519 SSH key pair with standard filenames
      ansible.builtin.openssh_keypair:
        path: /tmp/id_ed25519
        type: ed25519
      delegate_to: localhost
      run_once: true

    - name: Print the SSH public key amend it with the inventory_hostname for identification
      ansible.builtin.shell:
        cmd: echo "$(cat /tmp/id_ed25519.pub) {{ inventory_hostname }}"
      register: ssh_public_key_with_host
      delegate_to: localhost
      run_once: true

    - name: Print the SSH public key and prompt to add it
      ansible.builtin.shell:
        cmd: cat /tmp/id_ed25519.pub
      register: ssh_public_key
      delegate_to: localhost
      run_once: true

    - name: Prompt to add the SSH public key to the flake and secrets.nix
      ansible.builtin.pause:
        prompt: |
          Add the following SSH public key to secrets.nix for {{ inventory_hostname }}:
          {{ ssh_public_key_with_host.stdout }}
          Press enter once done.
      delegate_to: localhost
      run_once: true

    - name: Ensure the reencrypt_secret.sh script is present and executable
      copy:
        content: |
          #!/usr/bin/expect -f
          
          set timeout -1
          
          # Function to re-encrypt with agenix for a single secret
          proc reencrypt_secret {secret} {
              spawn agenix --rekey $secret
              expect "Enter passphrase for*"
              send -- "$::env(SSH_PASSPHRASE)\r"
              expect {
                  "Enter passphrase for*" { reencrypt_secret $secret }
                  eof
              }
          }
          
          # Prompt for the SSH passphrase
          puts -nonewline "Please enter your SSH passphrase: "
          stty -echo
          expect_user -re "(.*)\n"
          set SSH_PASSPHRASE $expect_out(1,string)
          stty echo
          puts ""
          
          # Change directory to ./secrets
          cd ./secrets
          
          # Get the list of secrets to re-encrypt
          set secrets [split [exec agenix --list] "\n"]
          
          # Re-encrypt each secret
          foreach secret $secrets {
              if {$secret ne ""} {
                  reencrypt_secret $secret
              }
          }
          
          # Check if any errors occurred during re-encryption
          if {[catch {expect eof}]} {
              puts "Re-encryption failed. Please run the script again or manually check the error."
              exit 1
          } else {
              puts "Re-encryption successful."
          }
        dest: /tmp/reencrypt_secret.sh
        mode: '0700'
      delegate_to: localhost
      run_once: true
      args:
        executable: /run/current-system/sw/bin/bash

    - name: Execute reencryption script
      ansible.builtin.shell: "/tmp/reencrypt_secret.sh"
      delegate_to: localhost
      run_once: true
      ignore_errors: true  # Consider handling errors more gracefully

    - name: Manual fallback prompt
      ansible.builtin.pause:
        prompt: "If the script did not run successfully, please run /tmp/reencrypt_secret.sh in a new terminal tab and press enter here once done."
      delegate_to: localhost
      when: "'Re-encryption successful.' not in hostvars[inventory_hostname].stderr"

    - name: Update known_hosts file to remove old host key
      ansible.builtin.shell: |
        ssh-keygen -R "{{ ansible_host }}"
      delegate_to: localhost
      args:
        executable: /run/current-system/sw/bin/bash

    - name: Temporarily make the private SSH key globally readable
      ansible.builtin.command: chmod 644 /tmp/id_ed25519
      delegate_to: localhost
      become: yes
      run_once: true
      args:
        executable: /run/current-system/sw/bin/bash

    - name: Copy the private SSH key to the target root account
      ansible.builtin.copy:
        src: /tmp/id_ed25519
        dest: /root/.ssh/id_ed25519
        mode: '0600'
      delegate_to: "{{ inventory_hostname }}"
      become: yes

    - name: Copy the public SSH key to the target root account
      ansible.builtin.copy:
        src: /tmp/id_ed25519.pub
        dest: /root/.ssh/id_ed25519.pub
        mode: '0644'
      delegate_to: "{{ inventory_hostname }}"
      become: yes

    - name: Revert private SSH key permissions
      ansible.builtin.command: chmod 600 /tmp/id_ed25519
      delegate_to: localhost
      become: yes
      run_once: true

    - name: Commit changes to the flake
      ansible.builtin.shell:
        cmd: git commit -a -Ss -m "Add SSH public key for {{ inventory_hostname }}"
      delegate_to: localhost
      args:
        executable: /run/current-system/sw/bin/bash

    - name: Install NixOS on the target machine using local clone of nixos-anywhere
      ansible.builtin.shell:
        cmd: >
          nix run ./ 
          --extra-experimental-features "nix-command flakes" --no-reboot
          -- --flake .#{{ inventory_hostname }}
          root@{{ ansible_host }}
      args:
        executable: /run/current-system/sw/bin/bash
      delegate_to: localhost

    - name: Copy the private SSH key to the target serveradmin account
      ansible.builtin.copy:
        src: /tmp/id_ed25519
        dest: /root/.ssh/id_ed25519
        mode: '0600'
      delegate_to: "{{ inventory_hostname }}"

    - name: Copy the public SSH key to the target serveradmin account
      ansible.builtin.copy:
        src: /tmp/id_ed25519.pub
        dest: /root/.ssh/id_ed25519.pub
      delegate_to: "{{ inventory_hostname }}"

    - name: Remove old private key in /tmp
      ansible.builtin.file:
        path: /tmp/id_ed25519
        state: absent
      delegate_to: localhost
      run_once: true
    
    - name: Remove old public key in /tmp
      ansible.builtin.file:
        path: /tmp/id_ed25519.pub
        state: absent
      delegate_to: localhost
      run_once: true

    # - name: Reboot

    # - name: Wait for the machine to reboot
    #   ansible.builtin.wait_for_connection:
    #     delay: 60
    #     timeout: 300

    # - name: Update known_hosts file to remove old host key
    #   ansible.builtin.shell: |
    #     ssh-keygen -f "$HOME/.ssh/known_hosts" -R "{{ ansible_host }}"
    #   delegate_to: localhost
      
    # - name: Apply custom flake configuration
    #   ansible.builtin.shell: |
    #     nixos-rebuild switch --flake github:blakeashleyjr/nix-infra#hv-2 --target-host root@{{ inventory_hostname }}
    #   args:
    #     executable: /run/current-system/sw/bin/bash
    #   environment:
    #     NIX_PATH: nixpkgs=channel:nixos-unstable

